title: Simulating Qubit Interaction Using Multimode C-QED
description: Summarizes the work done in as part of the Helen Edwards Summer Program.
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine
markdown: Kramdown
repository: SoumyaShreeram/Qubit